### ISSUE TITLE
Add wsWarning support for Struct Keys

### ISSUE THREAD

**Issue by JamoCA** [kwaschny/cf_dump#11]
A Lucee developer encountered an issue where he was getting an error when attempting to reference a struct key. In the end, it turned out the key had leading whitespace.  I was going to recommend using this library rather than the native dump tag, but decided to try it first and learned that the `wsWarning` flag does not extend to key names
https://dev.lucee.org/t/weird-struct-issue/12191

```cfc
a = [
	" test": 1
	,"test": " abc "
];
cf_dump(var=a);  // " abc " displays red periods to warn of whitespace, but the unique " test" key.
```

Should `wsWarning` be optionally extended to work with key names?

**Comment by kwaschny** [comment]
> Should `wsWarning` be optionally extended to work with key names?

That sounds like a good idea. I certainly would expect it to work on keys too.

I will extend `wsWarning` to accepting strings. Possible values then:

|         |                           |
| ------- | ------------------------- |
| `false` | no detection              |
| `key`   | detect in keys only       |
| `value` | detect in values only     |
| `true`  | detect in keys and values |

**Comment by kwaschny** [comment]
[Ready for testing](https://github.com/kwaschny/cf_dump/compare/master...11-wsWarning).

**Comment by JamoCA** [comment]
Looks good to me. It highlights struct keys w/leading or trailing whitespace (currently in my whitespace unit tests) for struct keys of all levels.

Here's a dump screenshot.

![cfdump-struct-whitepace-20230227055622](https://user-images.githubusercontent.com/1112671/221582799-18573b14-4c53-405b-84b0-7bed9efef963.png)
