### ISSUE TITLE
Data Types aren't being correctly identified.

### ISSUE THREAD

**Issue by JamoCA** [kwaschny/cf_dump#3]
Using ACF2016, I used `arraySetMetadata`/`setMetaData` to apply data types to values within an array. If I use `arrayGetMetaData`, I can verify that these data types are set, but cf_dump isn't consistently displaying the same results.

Shouldn't these match?  Or is Adobe doing something odd with how it's assigning the data types?

![CF_Dump_20210625114736](https://user-images.githubusercontent.com/1112671/123471786-2d3c9100-d5ab-11eb-9192-eb47abd98487.png)

Here's my visual unit test.

```
<cfset inputs = [
	"2500.12", 4.0, "Yes", "False", "339090",
	{"q1": "Yes"},
	["1","yes","3","no","null","null"]
]>
<cfset metadata={
	items: [
		"numeric", "integer", "string", "boolean", "string",
		{q1: {type:"string",ignore:true}},
		{items: ["integer","boolean","string","string","string","null"]}
	]
}>
<cfset inputs.setmetadata(metadata)>
<table>
	<tr valign="top">
		<td><cfdump var="#arrayGetMetaData(inputs)#" label="Dump arrayGetMetaData()"></td>
		<td><cf_dump var="#inputs#" label="cf_dump (types should match arrayGetMetaData())">
		</td>
	</tr>
</table>
```

**Comment by kwaschny** [comment]
ColdFusion doesn't touch your input when using `setMetaData`. It's really just adding meta information to the variable that is later used when casting (e.g. `serializeJSON`).

```
<cfset arrayWithRealInteger = [ createObject("java", "java.lang.Integer").init("123") ]>

<cfset arrayWithFakeInteger = [ "123" ]>
<cfset arraySetMetaData(arrayWithFakeInteger, { items: [ "integer" ] })>

<cfoutput>#arrayWithRealInteger[1].intValue()#</cfoutput>
<!--- outputs: 123 --->

<cfoutput>#arrayWithFakeInteger[1].intValue()#</cfoutput>
<!--- throws exception: The intValue method was not found. --->
```

Since `cf_dump` is only interested in the underlying Java class, the result is to be expected.

**Comment by JamoCA** [comment]
ok, that's good to know.  The ACF documentation isn't very clear in defining that this is a json-only-benefitting function.

I usually use `javacast("int", "123")` when manually creating values as I never know if the CFML that I write is going to be used in either Adobe ColdFusion _(which it typeless)_ or Lucee _(which handles values better IMHO)_.  I've also found that javacasting is critical when creating query objects or else future query-of-queries on that object will fail and throw CF errors.  (ie, you can insert a STRING value into an INT column and loop/output it, but the query object can now no longer be manipulated via QoQ.)
