### ISSUE TITLE
PCI Compliant & Redaction Feature Suggestion

### ISSUE THREAD

**Issue by JamoCA** [kwaschny/cf_dump#4]
In order to prevent output from being generated with sensitive information (ie, logging or sending via email with CC, SSN, app tokens, etc), I currently do the following and wondered if you could implement in your project.  (If preferred, I could do a pull request.)

## Capture the output of cf_dump and filter using maskCC UDF:
```
<cfscript>
string function jreEscape(required string text="") output=false hint="alternative to ACF-only reEscape()" {
	return rereplace(javacast("string", arguments.text), "(?=[\[\]\\^$.|?*+()])", "\", "all");
}

string function maskCC(required string html) output=false hint="I use regex to detect and suppress CC numbers" {
	var local.response = javacast("string", arguments.html);
	local.testCCs = reMatch("\b(?:\d[ -]*?){13,16}\b", local.response);
	if (arrayLen(local.TestCCs)){
		for (local.thisCC in local.testCCs) {
			local.cleanNum = local.thisCC.replaceAll("\D", "");
			if( isValid("creditcard", local.cleanNum )){
				local.response = local.response.replaceAll(jreEscape(local.thisCC), "\*\*\*\*\*\*\*\*\*\*\*\*" & jreEscape(right(local.cleanNum,4)));
			}
		}
	}
	return local.response;
}

// writeoutput(maskCC("<div>4444333322221111</div>"));
// The above outputs "<div>************1111</div>"

</cfscript>
```

## Add support for "RedactedKeys" argument. (default: `CVV2,CC_CVV2,SecurityCode,SSN`)

When outputting the values, if a keyname matches (`redactedKeys.keyExists(keyName)`) then coerce the output to be the string `[REDACTED]`.

**Comment by kwaschny** [comment]
Good idea. We usually redact sensitive information before passing it to output, but I can see myself using this too.

I would rather want to do it in a dynamic way though. I'm thinking of a hook/callback that let's you detect and rewrite values yourself. Requirements vary from project to project, so do patterns for detecting.

Consider this:
```
<cfscript>

    function redactCC(value) {
    
        if (UDF.isCreditCard(value)) {
        
            return UDF.maskCreditCard(value);
        }
    
        return value;
    }
    
    function anonymizeNames(value, key) {
    
        if (key eq "firstName") {
        
            firstNames = [ "John", "Jane" ];
            return firstNames[randRange(1, arrayLen(firstNames))];
        }
        if (key eq "lastName") {
        
            lastNames = [ "Doe", "Miles" ];
            return lastNames[randRange(1, arrayLen(lastNames))];
        }
    
        return value;
    }

</cfscript>

<cf_dump redact="#[ redactCC, anonymizeNames ]#" var="#data#">
```
Looks good? You could put the hooks into REQUEST scope to not have them pass to `<cf_dump>` everytime, just like all the other attributes.

----

As for the "RedactedKeys" argument: Do you just want to distinguish between blacklisted and redacted? Having the hook that also passes they key would probably cover this functionality. As for defaults: Locale specific things do not belong into defaults according to my design philosophy.

**Comment by JamoCA** [comment]
As a custom tag, I'd prefer to have it stand on its own and be able to be used anywhere without worrying about the framework used or whether function pre-exist in order to be passed.  Example: If I set up a simple "ECHO.cfm" template and used no framework or Application.cfc (other than cf_dump and/or CFMAIL), I'd want to have sensitive keynames redacted (by name) & remove plaintext CCs from the generated output automatically.

Extending support for custom redaction methods (other than just CC's) would be nice.

A function like anonymization (ie, faker) should probably be done before being passed to cf_dump since it _modifies values_ versus _suppression/redaction_ for compliance/pci/privacy reasons.

Regarding redacting, you are correct.  It performs the same function and the only difference is the visible text that we currently use.  I didn't think to use the word "[blacklisted](https://www.merriam-webster.com/dictionary/blacklist)" for the suppression of data as "[redacted](https://www.merriam-webster.com/dictionary/redacted)" seemed to be the more appropriate word.

Regarding defaults, it may be best to avoid, but in cases where I've done this, I've used a keyword to use dictionaries of popular matching variable names that I've seen commonly used amongst all payment gateways.  These key field names are usually the same regardless of the preferred language of the developer. _(ie, Google, Authorize.net & PayPal APIs functions and key names are standardized in English and they don't offer language-specific API endpoints to service different locales.  The values change based on locale, not the key names.)_  In our use cases, we'd rather overreach than accidentally leak sensitive information because we neglected to remember to update the keys that are manually passed. _(I'd prefer to update a single CFTag than search and update how it's being used everywhere.)_

Perhaps this would be better integrated as a separate redaction module entirely.  I could integrate our existing logic by creating a separate CFC and then rewriting `attributes.var` at the beginning of the cf_dump CFC. _(This would make it easier for me to update whenever there's a new release of cf_dump and I'd never have to worry about framework or request-level functions existing.)_

**Comment by kwaschny** [comment]
I implemented the feature as `rewrite` attribute that takes callback functions via array in this [Branch](https://github.com/kwaschny/cf_dump/tree/feature/rewrite#rewrite) 432a7b897418c872b641ac9526a21813b8788282. I didn't spend too much time testing it (`null` might throw errors), so don't use it in production before testing with your data. Feel free to break it, so I can fix the cases I missed.

> As a custom tag, I'd prefer to have it stand on its own [...] Perhaps this would be better integrated as a separate redaction module entirely.

Yes, I suggest you to hardcode your functions into the tag then. You can just add them as default callbacks into `ATTRIBUTES.rewrite` within the dump tag file.

> Regarding redacting, [...] It performs the same function and the only difference is the visible text that we currently use.

Use a callback then and rewrite values to `[REDACTED]` whenever the key matches, like: 
 ```
function doTheDiddley() {
    if ((ARGUMENTS.context eq "struct") and arrayFindNoCase([ "CVV2", "SSN" ], ARGUMENTS.data) { return "[REDACTED]"; }
    return ARGUMENTS.value;
}
```

> These key field names are usually the same regardless of the preferred language of the developer. [...] The values change based on locale, not the key names.

I assume you are from the US? Because the sad reality is that we still have to work with old and even newer APIs and endpoints that use mixed language or plain German tag and key names. It's awful and probably written by some senior devs from the 90s that also named all their variables like this because they barely speak English. The XML we are working with is literally all German. Well XML via SOAP API already gives it away, I guess. 🤪

So if I wanted to redact health insurance related data for example, I'd need a bigger list of potential keys. But I get what you are saying. If it works for you, go for it. We haven't touched payment related data for some time as the GDPR in EU has become a minefield and a risk you don't want to take.
