### ISSUE TITLE
Select/Copy/Paste Behavior of Dump Output

### ISSUE THREAD

**Issue by JamoCA** [kwaschny/cf_dump#5]
Has there been any consideration for an option to allow a "more simple" dump?  (ie, suppressed display of data type)

In some cases, I still prefer to use the original ACF CFDump because I can select the FORM/URL/Struct data on the screen and quickly paste it into my dev tools (each row is pasted as `varName+Tab+value`).  I attempted to reduce the table-within-table effect by removing "colheader" and outputting the value, but the modified DIV hierarchy that uses the existing CSS results in a weird looking dump.  Even with the just the data type div suppresses, the output results in a single column of pasted data.

NOTE:  If you still desire to visually denote the data type, a decorator that I've used in the past is a slightly thicker + colored border between the variable name and the value.

Thoughts?

**Comment by kwaschny** [comment]
Not exactly sure what your desired output is supposed to look like, but did you try
```
.col.colheader {
    display: none;
}
```
?

**Comment by JamoCA** [comment]
I tested this by omitting `div.colheader` from the output. I don't think it makes much difference as the "display:table" rules don't apply to content when copying and it results in each var name, data type and values ending up on their own lines rather than tabbed output that you would expect when copying data from an HTML table.

Please render the following tables and compare the behavior when copying & pasting data:

## CFDump HTML(using TABLE)
```html
<table class="cfdump_struct">
	<tr><th colspan="2" >struct (ordered)</th></tr>
	<tr>
		<td>a</td>
		<td>1</td>
	</tr>
	<tr>
		<td>b</td>
		<td>2</td>
	</tr>
	<tr>
		<td>c</td>
		<td>3</td>
	</tr>
</table>
```
## CFDUMP Copy/Paste Output 
```
a	1
```


## cf_dump HTML (using DIVs with CSS code to render "like a table")
```html
<div class="cf_dump">
	<div class="var struct" style="display:table;">
		<!--- <div class="col colheader" style="display:table-caption;">
			<span class="type">struct [3]</span> <span class="subtype">coldfusion.runtime.StructOrdered</span> <span class="ref">@281631353</span>
		</div> --->
		<div class="row" style="display:table-row">
			<div class="rowheader" style="display:table-cell;">
			a
			</div>
			<div class="rowcell" style="display:table-cell;">
				<div title="" class="var string" style="display:table;">
					<!--- <div class="col colheader" style="display:table-caption;">
						<span class="type">string &#x5b;1&#x5d;</span> <span class="subtype"></span>
					</div> --->
					<div class="row" style="display:table-row">
						<div class="rowcell" style="display:table-cell;">
						1
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
```
## cf_dump Copy/Paste Output (even more verbose when "colheader" is included)
```
a
1
```

While a javascript "copy data to clipboard" function could be added and would be beneficial, this approach could be used in environments that don't allow javascript execution (ie, email message).

I really like the extra data type information, but the output from cf_dump isn't useable beyond viewing.  I routinely copy results directly from CFDUMP to paste into Excel and/or other online forms. I'm not sure if this is any way around this other than to switch to tables.  _(I wrote a CF_Dumplite CFTag that uses tables, is copy/paste friendly and works well with simpler objects, but it lacks many of the features that your tag has.  I was hoping to abandon my tag and use your instead.)_

**Comment by kwaschny** [comment]
Ah my bad, I misunderstood the issue. Well, I don't think it's that bad. Lucee's dump has a similar behavior with the newlines. And once you have nested data, even copy/paste of the ACF dump won't look any good.

I certainly do not consider rewriting the dump's DOM just to make the copy/paste look "nicer".

> the output from cf_dump isn't useable beyond viewing

And it was never intended to do anything else. 🙂

> Has there been any consideration for an option to allow a "more simple" dump?

No. Quoting from my README:  
_"This custom tag [...] offers more insight and usually renders faster than the native (ACF) cfdump."_

If I neither need the data types nor the faster output (`<cfdump>` in ACF 10 can be slow to a point where it causes request timeouts, ridiculous!), I just use the regular tag or serialize to JSON for export cases.
