### ISSUE TITLE
Useage?

### ISSUE THREAD

**Issue by PwrSrg** [kwaschny/cf_dump#6]
How do I use this?

Thanks!

**Comment by kwaschny** [comment]
Three options:
1. Put the `dump.cfm` into any folder and add that path via [ColdFusion Admin section for custom tags](https://www.cfguide.io/coldfusion-administrator/extensions-custom-tag-paths/).
2. Put the `dump.cfm` into your project folder and utilize [Application.cfc's `this.customTagPaths`](https://helpx.adobe.com/de/coldfusion/developing-applications/developing-cfml-applications/designing-and-optimizing-a-coldfusion-application/elements-of-a-coldfusion-application.html).
3. Put the `dump.cfm` in the folder you want to use it in.
