### ISSUE TITLE
Java method security exception

### ISSUE THREAD

**Issue by disccomp** [kwaschny/cf_dump#7]
dump.cfm : line 323 and 1011

Coldfusion 2016, With "Disable access to internal ColdFusion Java components" turned off, works, but not best practice.

Potential solution, wrap those calls in a try/catch:
``` coldfusion
<cftry>
	<cfset LOCAL.subType  = ARGUMENTS.var.getClass().getName()>
<cfcatch type="any">
	<cfset LOCAL.subType  = ""/>
</cfcatch>
</cftry>

```

**Comment by kwaschny** [comment]
Fixed by 877bc9e59cec29bd0ed66a58ce5dd6eda8566719.
